### ISSUE TITLE
[Minor Bug] I cannot dislike after liking or like after disliking a resume. 

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [levys19/Cracking_the_resume#238]
# Description

After creating an account, I checked out other resumes. When I pressed on dislike, I could not again like it. 

# Video Demonstration of the bug

I have uploaded a video of the bug that I am facing with the zip file that is attached below. 

[crackingtheresume(minor bug).zip](https://github.com/levys19/Cracking_the_resume/files/1911703/crackingtheresume.minor.bug.zip)

**Comment by shallyguo** [comment]
Hi, our initial intentions for the like/dislike functionalities were similar to how the piazza voting system works--the user can only like or dislike a resume once and after they have made their choice, they cannot go back and change their answers. I think our initial implementation of this might have been confusing since after voting, the buttons are still visible on the page. But we believe that the new changes better reflect our intentions. Nonetheless, thank you for reporting this bug!
