### ISSUE TITLE
bug report (Alpha testing)

### ISSUE THREAD

**Issue by viyer5** [levys19/Cracking_the_resume#241]
**_Email Validation_**

There is no form of email validation whatsoever on this website. I tried creating an account using 1@1.com and the website let me register without any issues. Please look into it

**Comment by levys19** [comment]
We will look into it. Thank you for reporting the bug.

**Comment by shallyguo** [comment]
Hi, we have decided to remove the email address field from our signup page because our current version of our application does not require the use of our user's email, thus optimizing our database to contain only essential user information. Thank you again for reporting the bug and making a contribution to the improvement of our application!
