### ISSUE TITLE
Bug: No check for valid email address

### ISSUE THREAD

**Issue by Manvijay** [levys19/Cracking_the_resume#247]
While registering anyone can register with any dummy id like I did with hhghghgg@kk . You guys should look into this. Good Luck with the project!

**Comment by lieselva** [comment]
Thank you for reporting the bug.

**Comment by shallyguo** [comment]
Hi, we have decided to remove the email address field from our signup page because our current version of our application does not require the use of our user's email, thus optimizing our database to contain only essential user information. Thank you again for reporting the bug and making a contribution to the improvement of our application!
